# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:13
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5000:5432"
    environment:
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
    volumes:
      - fk-odoo-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  fk-odoo-data: